repos:
  # JavaScript/TypeScript (React)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.50.0"
    hooks:
      - id: eslint
        args: [--ext, ".js,.jsx,.ts,.tsx"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        args: [--write]

  # Python hooks
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.1"
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        args: [--strict]

  # Common hooks (for all file types)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
